// site/src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	/**
	 * One button, four voices. Primary is the only saturated colour on the
	 * page — it means "act". `loading` swaps the label without changing width.
	 */
	let {
		href,
		variant = 'primary',
		size = 'md',
		loading = false,
		disabled = false,
		type = 'button',
		class: cls = '',
		children,
		...rest
	}: {
		href?: string;
		variant?: 'primary' | 'secondary' | 'ghost' | 'link';
		size?: 'sm' | 'md' | 'lg';
		loading?: boolean;
		disabled?: boolean;
		type?: 'button' | 'submit';
		class?: string;
		children: Snippet;
		[key: string]: unknown;
	} = $props();

	const base = 'group relative inline-flex items-center justify-center gap-2 rounded-full font-semibold transition-[background-color,border-color,color,transform,box-shadow] duration-200 ease-[var(--ease-standard)] focus-visible:outline-2 disabled:pointer-events-none disabled:opacity-50';
	const variants = {
		primary: 'bg-accent text-accent-ink shadow-[0_8px_24px_-10px_var(--color-accent)] hover:-translate-y-px hover:shadow-[0_12px_28px_-10px_var(--color-accent)] active:translate-y-0',
		secondary: 'border border-line-strong bg-surface-2 text-ink hover:border-accent/60 hover:bg-surface-3',
		ghost: 'text-ink-2 hover:bg-surface-2 hover:text-ink',
		link: 'text-accent underline-offset-4 hover:underline'
	};
	const sizes = { sm: 'h-9 px-4 text-[13px]', md: 'h-11 px-5 text-[14px]', lg: 'h-13 px-7 text-[15px]' };
	const classes = $derived(`${base} ${variants[variant]} ${sizes[size]} ${cls}`);
</script>

{#if href}
	<a {href} class={classes} aria-disabled={disabled || undefined} {...rest}>
		{@render children()}
	</a>
{:else}
	<button {type} class={classes} disabled={disabled || loading} aria-busy={loading || undefined} {...rest}>
		<span class={loading ? 'invisible' : ''}>{@render children()}</span>
		{#if loading}
			<span class="absolute inset-0 flex items-center justify-center gap-1" aria-hidden="true">
				{#each [0, 1, 2] as i}<span class="h-1.5 w-1.5 rounded-full bg-current animate-blink" style={`animation-delay:${i * 150}ms`}></span>{/each}
			</span>
		{/if}
	</button>
{/if}

// src/components/ui/button.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "relative inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-sm font-medium transition-[background-color,color,border-color,box-shadow,transform,opacity] duration-200 ease-[var(--ease-out-expo)] active:scale-[0.985] disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/50 [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        primary:
          "bg-accent text-accent-foreground shadow-[0_1px_0_rgba(255,255,255,0.12)_inset,0_8px_24px_-12px_var(--accent)] hover:brightness-110",
        gradient:
          "bg-[linear-gradient(120deg,var(--accent),var(--accent-2))] text-white shadow-[0_1px_0_rgba(255,255,255,0.18)_inset,0_12px_32px_-12px_var(--accent)] hover:brightness-110",
        secondary: "border border-border bg-card text-foreground hover:border-border-strong hover:bg-muted/60",
        ghost: "bg-transparent text-muted-foreground hover:bg-muted hover:text-foreground",
        outline: "border border-border bg-transparent text-foreground hover:bg-muted/60",
        danger: "bg-danger text-white hover:brightness-110",
        link: "h-auto p-0 text-accent underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 px-3 text-[13px]",
        lg: "h-11 px-6 text-[15px] rounded-xl",
        xl: "h-12 px-7 text-[15px] rounded-full",
        icon: "h-9 w-9",
        "icon-sm": "h-8 w-8",
      },
      pill: {
        true: "rounded-full",
        false: "",
      },
    },
    defaultVariants: {
      variant: "secondary",
      size: "default",
      pill: false,
    },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
  /** Shows a spinner and disables the button. */
  loading?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, pill, asChild = false, loading = false, disabled, children, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, pill, className }))}
        ref={ref}
        disabled={disabled || loading}
        aria-busy={loading || undefined}
        {...props}
      >
        {/* Slot requires exactly one child, so the spinner only exists on real buttons. */}
        {asChild ? (
          children
        ) : (
          <>
            {loading && <Loader2 className="animate-spin" aria-hidden />}
            {children}
          </>
        )}
      </Comp>
    );
  }
);
Button.displayName = "Button";

export { Button, buttonVariants };
